# ------------------------------------------------------------------------------
# pre-commit configuration file
# Enforces formatting, linting, and secret scanning on commit.
# Hooks run locally before code is committed.
# Requires: `pre-commit install` and activated `.venv`
# ------------------------------------------------------------------------------

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: trufflehog-pwsh
        name: TruffleHog Custom PowerShell Hook
        entry: pwsh scripts/githooks/trufflehog-pre-commit.ps1
        language: system
        types: [text]
        always_run: true
        pass_filenames: false
