# .github/workflows/ci-dev.yml
name: Dev Branch CI

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

      - name: Lint code
        run: flake8 src scripts config tests

      - name: Security scan (Bandit)
        run: bandit -r src scripts

      - name: Run tests
        run: pytest --tb=short --disable-warnings

      - name: Secret scan (TruffleHog, dev-only scope)
        run: |
          git fetch --unshallow || true
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            ghcr.io/trufflesecurity/trufflehog:latest \
            git file://. --since-commit=HEAD~10 --json
