# ────────────────────────────────────────────────
# Workflow: Dev CI
# Purpose : Lint and test Python code on dev branches and PRs
# Trigger : push to dev branches, pull_request to main
# ────────────────────────────────────────────────
name: Dev CI

on:
  push:
    branches: 
      - feature
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

      - name: Lint code
        # Only lint existing folders
        run: flake8 $(find src config tests -type d -maxdepth 0 2>/dev/null)

      - name: Security scan (Bandit)
        run: bandit -r src 

      - name: Run tests
        run: pytest --tb=short --disable-warnings

      - name: Secret scan (TruffleHog, dev-only scope)
        run: |
          git fetch --unshallow || true
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            ghcr.io/trufflesecurity/trufflehog:latest \
            git file://. --since-commit=HEAD~10 --json
