# ────────────────────────────────────────────────
# Workflow: Dev CI
# Purpose : Lint and test Python code on dev branches and PRs
# Trigger : push to dev branches, pull_request to main
# ────────────────────────────────────────────────
name: Dev CI

on:
  push:
    branches: 
      - main
      - feature
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

          # Install TruffleHog using shared script
          chmod +x scripts/shared/trufflehog-install.sh
          scripts/shared/trufflehog-install.sh

      - name: Run TruffleHog scan
        run: |
          chmod +x ./scripts/shared/trufflehog-wrapper.sh
          ./scripts/shared/trufflehog-wrapper.sh --log logs/trufflehog-scan.json || echo "Scan completed with warnings"

      - name: Lint code
        # Only lint existing folders
        run: flake8 --config=.flake8 $(find src config tests -type d -maxdepth 0 2>/dev/null)

      - name: Security scan (Bandit)
        run: bandit -r src 

      - name: Load .env
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables from .env"
            set -a
            source .env
            set +a
          else
            echo "Warning: .env file not found. Skipping env load."
          fi
