# .github/workflows/docker-build.yml
name: Dev Docker Build

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'  # for prerelease tags like v0.1.0-dev

jobs:
  docker-lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t devops-world:dev .
