# ────────────────────────────────────────────────
# Workflow: Docker Release
# Purpose : Build and push Docker image on main and release branches
# Trigger : push to main, release/*
# ────────────────────────────────────────────────
on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # caching/flexibility
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t devops-world:latest .
          docker tag devops-world:latest itbyteenthusiast/devops-world:latest
          docker push itbyteenthusiast/devops-world:latest
