# ────────────────────────────────────────────────
# Workflow: PR Validation
# Purpose : Lint and build Dockerfile in pull requests
# Trigger : pull_request targeting main
# ────────────────────────────────────────────────
name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint (containerized)
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker image with PR tag
        run: |
          echo "Triggered by PR #${{ github.event.pull_request.number }}"
          docker build -t devops-world:pr-${{ github.event.pull_request.number }} .
