name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint (Docker)
        run: docker run --rm -i hadolint/hadolint < Dockerfile
