# ────────────────────────────────────────────────
# Workflow: security_scan.yml
# Purpose : Run security scans on the codebase
# Trigger : push to main, pull_request to main
# ────────────────────────────────────────────────
name: Security Scanning Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

          # Install TruffleHog using shared script
          chmod +x scripts/shared/trufflehog-install.sh
          scripts/shared/trufflehog-install.sh

      - name: Run TruffleHog scan
        run: |
          chmod +x ./scripts/shared/trufflehog-wrapper.sh
          ./scripts/shared/trufflehog-wrapper.sh --log logs/trufflehog-scan.json || echo "Scan completed with warnings"

      - name: Run Bandit scan (optional for Python code security)
        run: |
          bandit -r . -s B101

      - name: Upload TruffleHog results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: logs/trufflehog_scan.json
