# ────────────────────────────────────────────────
# Workflow: security_scan.yml
# Purpose : Run security scans on the codebase
# Trigger : push to main, pull_request to main
# ────────────────────────────────────────────────
name: Security Scanning Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

          # Download the correct Linux binary for TruffleHog v3.89.2
          curl -L https://github.com/trufflesecurity/trufflehog/releases/download/v3.89.2/trufflehog_3.89.2_linux_amd64.tar.gz -o trufflehog.tar.gz
          tar -xzf trufflehog.tar.gz
          chmod +x trufflehog
          mv trufflehog /usr/local/bin/trufflehog

          # Confirm it’s a valid executable
          file /usr/local/bin/trufflehog | grep 'ELF' || { echo "❌ Invalid binary. Download failed."; exit 1; }

      - name: Run TruffleHog scan
        run: ./scripts/shared/trufflehog_wrapper.sh --log logs/trufflehog_scan.json

      - name: Run Bandit scan (optional for Python code security)
        run: |
          bandit -r .

      - name: Upload TruffleHog results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: logs/trufflehog_scan.json
